FROM node:16-bullseye as build
WORKDIR /app
COPY ./package*.json ./
RUN npm install
COPY ./ ./
RUN npm run build

FROM node:16-bullseye as production
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY ./package*.json ./
RUN npm install --only=production
EXPOSE 3000
CMD ["npm", "run", "start"]
